default_stages: [commit]
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 21.4b2
    hooks:
    - id: black
      language_version: python3.6
  - repo: local
    hooks:
      - id: add-py-license-header
        name: add py license header
        entry: python scripts/add_py_license_header.py docs/license-headers/license.py ./ ".*\.py$" ".*" 'Tencent is pleased to support'
        language: system
        types: [ python ]
      - id: check-migrate
        name: check migrate
        entry: python scripts/check_migrate/check_migrate.py
        language: system
        types: [python]
      - id: check-commit-message
        name: Check commit message
        entry: python scripts/check_commit_message.py
        language: system
        stages: [commit-msg]
      - id: ip
        name: Check ip
        description: Check ip
        entry: scripts/sensitive_info_check/ip.sh
        language: script
        exclude: |
          (?x)(
             ^scripts/sensitive_info_check/|
             tests/.*.py|
             requirements.txt|
             bin/prom-aggregation-gateway
          )
