  multipass: true
  plugins: [
      {
          inlineStyles: {
              onlyMatchedOnce: false
          }
      },
      {
          cleanupAttrs: true
      },
      {
          removeDoctype: true
      },
      {
          removeXMLProcInst: true
      },
      {
          removeComments: true
      },
      {
          removeMetadata: true
      },
      {
          removeTitle: true
      },
      {
          removeDesc: true
      },
      {
          removeUselessDefs: true
      },
      {
          removeEditorsNSData: true
      },
      {
          removeEmptyAttrs: true
      },
      {
          removeHiddenElems: true
      },
      {
          removeEmptyText: true
      },
      {
          removeEmptyContainers: true
      },
      {
          removeViewBox: false
      },
      {
          cleanupEnableBackground: true
      },
      {
          convertStyleToAttrs: true
      },
      {
          convertColors: true
      },
      {
          convertPathData: false
      },
      {
          convertTransform: true
      },
      {
          removeUnknownsAndDefaults: true
      },
      {
          removeNonInheritableGroupAttrs: true
      },
      {
          removeUselessStrokeAndFill: true
      },
      {
          removeUnusedNS: true
      },
      {
          cleanupIDs: true
      },
      {
          cleanupNumericValues: true
      },
      {
          moveElemsAttrsToGroup: true
      },
      {
          moveGroupAttrsToElems: true
      },
      {
          removeRasterImages: false
      },
      {
          mergePaths: false
      },
      {
          convertShapeToPath: true
      },
      {
          convertEllipseToCircle: true
      },
      {
          sortAttrs: true
      },
      {
          collapseGroups: true
      },
      {
          removeDimensions: true
      },
      {
          removeStyleElement: true
      },
      {
          sortDefsChildren: true
      },
      {
          reusePaths: false
      },
      {
          removeAttrs: { attrs: '(stroke|fill|data-name)' }
      }
  ]